### PR TITLE
Review runafluid imas

### PR DESCRIPTION
**Pull request by olaszsoma**
The Runafluid Kepler workflow bug has been fixed, it works now.  The modifications can be merged to master, and they can be tested (after or before merging). The results coming out of the workflow are to be validated, I have not checked them yet. At the moment, the message composer only produces a True output. Should I check the message output before merging?

### CODE REVIEW

**Comment by olaszsoma** [comment]
The testing of Runafluid Kepler workflow in IMAS environment has to be done before merging into master. The Kepler workflow doesn't crash anymore, but the output is not correct at the moment.
The output runaway density and current are zero regardless of the input electric field. I think the reason for this is, that the input total electron density is zero in the test IDS (which has been filled manually in order to be able to run the workflow), but the code and the input distribution IDS has to be reviewed to be sure.

**Comment by olaszsoma** [comment]
The input distribution is not zero, so that is not the problem.

**Comment by olaszsoma** [comment]
The reason why the output IDS had zero runaway density is the choice of the (normalized) radial coordinates. The second coordinate was above the maximum rho, so the density was set zero after calculation. The first coordinate was 0 and for some reason, the runaway calculation did not work for that (gave NaN value). Hence the program thought that the runaway population was negligible, and set it to zero.
The program works fine if the lower coordinate is not zero, but something else. I propose the merge to be done after the changes in the script have been committed, but before release thorough testing is needed on both environments.

**Review by gergopokol — APPROVED** [review]
Discussed...

**Pull request merged**
